#!/usr/bin/env python3
"""Draft Nature-style GMNPS main figures from existing manuscript source data.

This script intentionally reads only curated source-data files from
``outputs/nature_source_data_v2``. Data products are generated by
``build_nature_source_data_v2.py`` from reproduced scoring, validation and
digital-gut-twin outputs.
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


PALETTE = {
    "ink": "#222222",
    "muted": "#6A6A6A",
    "line": "#D6D6D6",
    "blue": "#2E6FAD",
    "blue_light": "#CFE1F2",
    "green": "#3F8F6B",
    "green_light": "#CDE8D8",
    "red": "#B44E4B",
    "red_light": "#F1CECB",
    "gold": "#C9972B",
    "gold_light": "#F2E2B8",
    "gray": "#C9C9C9",
    "pale": "#F6F6F3",
}


GROUP_ORDER = [
    "0000_Beverages",
    "1000_Grains",
    "2000_Fruit",
    "3000_Vegetables",
    "4000_LegNut",
    "5000_MPE",
    "5800_Seafood",
    "6000_Dairy",
    "7000_Fats Oils",
    "8000_Mixed",
    "8600_SauceCondiment",
    "9000_SavorySweet",
]


GROUP_LABELS = {
    "0000_Beverages": "Beverages",
    "1000_Grains": "Grains",
    "2000_Fruit": "Fruit",
    "3000_Vegetables": "Vegetables",
    "4000_LegNut": "Legumes/nuts",
    "5000_MPE": "Meat/poultry/eggs",
    "5800_Seafood": "Seafood",
    "6000_Dairy": "Dairy",
    "7000_Fats Oils": "Fats/oils",
    "8000_Mixed": "Mixed dishes",
    "8600_SauceCondiment": "Sauces/condiments",
    "9000_SavorySweet": "Savory/sweet",
}


def set_style() -> None:
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
            "font.size": 7,
            "axes.spines.right": False,
            "axes.spines.top": False,
            "axes.linewidth": 0.7,
            "axes.edgecolor": PALETTE["ink"],
            "xtick.color": PALETTE["ink"],
            "ytick.color": PALETTE["ink"],
            "text.color": PALETTE["ink"],
            "legend.frameon": False,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
        }
    )


def source_path(source_dir: Path, filename: str) -> Path:
    path = source_dir / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing source data file: {path}")
    return path


def read_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def save_figure(fig: plt.Figure, out_dir: Path, stem: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_dir / f"{stem}.svg", bbox_inches="tight")
    fig.savefig(out_dir / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(out_dir / f"{stem}.png", dpi=600, bbox_inches="tight")
    plt.close(fig)


def panel_label(ax: plt.Axes, label: str) -> None:
    ax.text(-0.08, 1.06, label, transform=ax.transAxes, fontweight="bold", fontsize=9, va="top")


def hero_label(ax: plt.Axes, label: str) -> None:
    ax.text(-0.035, 1.025, label, transform=ax.transAxes, fontweight="bold", fontsize=10, va="top")


def short_food_name(value: object, limit: int = 40) -> str:
    text = str(value)
    return text if len(text) <= limit else f"{text[: limit - 1]}."


def ordered_groups(frame: pd.DataFrame) -> pd.DataFrame:
    observed = list(frame["food_group"].dropna().unique())
    order = [group for group in GROUP_ORDER if group in observed]
    order.extend(sorted(group for group in observed if group not in order))
    return frame.set_index("food_group").reindex(order).dropna(subset=["n_foods"])


def add_hero_note(ax: plt.Axes, text: str, loc: tuple[float, float] = (0.03, 0.96)) -> None:
    ax.text(
        loc[0],
        loc[1],
        text,
        transform=ax.transAxes,
        va="top",
        ha="left",
        fontsize=8,
        bbox={"facecolor": "white", "edgecolor": PALETTE["line"], "boxstyle": "round,pad=0.35"},
    )


def figure_1_framework(source_dir: Path, out_dir: Path) -> None:
    summary = pd.read_csv(source_path(source_dir, "figure2_3_food_summary_v4.csv"))
    mask_counts = pd.read_csv(source_path(source_dir, "figure1_mask_counts.csv"))
    examples = pd.read_csv(source_path(source_dir, "figure1_individual_food_examples.csv"))

    fig = plt.figure(figsize=(7.4, 5.0))
    gs = fig.add_gridspec(2, 3, height_ratios=[1.32, 1.0], width_ratios=[1.0, 1.0, 1.0])

    ax = fig.add_subplot(gs[0, :])
    ax.set_axis_off()
    hero_label(ax, "a")
    ax.text(
        0.5,
        0.92,
        "Anchored personalized calibration",
        ha="center",
        va="top",
        fontsize=13,
        fontweight="bold",
        transform=ax.transAxes,
    )
    boxes = [
        (0.04, 0.43, 0.23, 0.28, "Population prior", "food-level baseline\n1-100 scale", PALETTE["blue_light"]),
        (0.39, 0.43, 0.23, 0.28, "Bounded deviation", "microbiome-calibrated\nfood response", PALETTE["green_light"]),
        (0.74, 0.43, 0.22, 0.28, "GMNPS", "prior retained plus\nindividual calibration", PALETTE["gold_light"]),
    ]
    for x0, y0, width, height, title, body, color in boxes:
        ax.add_patch(
            plt.Rectangle(
                (x0, y0),
                width,
                height,
                transform=ax.transAxes,
                facecolor=color,
                edgecolor=PALETTE["ink"],
                linewidth=0.9,
            )
        )
        ax.text(x0 + width / 2, y0 + height * 0.66, title, ha="center", va="center", fontweight="bold", transform=ax.transAxes)
        ax.text(x0 + width / 2, y0 + height * 0.34, body, ha="center", va="center", color=PALETTE["muted"], transform=ax.transAxes)
    ax.annotate("", xy=(0.37, 0.57), xytext=(0.29, 0.57), xycoords=ax.transAxes, arrowprops={"arrowstyle": "->", "lw": 1.3})
    ax.annotate("", xy=(0.72, 0.57), xytext=(0.64, 0.57), xycoords=ax.transAxes, arrowprops={"arrowstyle": "->", "lw": 1.3})
    ax.text(
        0.5,
        0.22,
        r"$\mathrm{score}_{ij}=\mathrm{clip}_{1,100}(\mathrm{baseline}_{j} + 12\tanh(Z_{ij}/2))$",
        ha="center",
        va="center",
        fontsize=11,
        transform=ax.transAxes,
    )
    ax.text(0.5, 0.08, "Deviation is centered within food, so the population mean remains anchored.", ha="center", va="center", color=PALETTE["muted"], transform=ax.transAxes)

    ax = fig.add_subplot(gs[1, 0])
    z = np.linspace(-4, 4, 400)
    deviation = 12 * np.tanh(z / 2)
    ax.plot(z, deviation, color=PALETTE["blue"], lw=1.9)
    ax.axhline(12, color=PALETTE["red"], lw=0.8, ls=":")
    ax.axhline(-12, color=PALETTE["red"], lw=0.8, ls=":")
    ax.axhline(0, color=PALETTE["line"], lw=0.8)
    ax.set_xlabel("Robust z-score")
    ax.set_ylabel("Score deviation")
    ax.set_title("Bounded transform")
    panel_label(ax, "b")

    ax = fig.add_subplot(gs[1, 1])
    label_map = {
        "microbiota-accessible and plant matrix": "MAC/\nplant matrix",
        "lipid and bile-acid related": "Lipid/\nbile acid",
        "not in primary channel": "Excluded\nfrom primary",
    }
    mask_counts = mask_counts.sort_values("n_nutrients", ascending=False)
    colors = [PALETTE["red_light"] if "lipid" in channel else PALETTE["green_light"] if "plant" in channel else PALETTE["gray"] for channel in mask_counts["channel"]]
    ax.bar(range(len(mask_counts)), mask_counts["n_nutrients"], color=colors, edgecolor=PALETTE["ink"], linewidth=0.6)
    ax.set_xticks(range(len(mask_counts)), [label_map.get(v, v) for v in mask_counts["channel"]])
    ax.set_ylabel("Nutrients")
    ax.set_title("Expert-revised channel boundary")
    panel_label(ax, "c")

    ax = fig.add_subplot(gs[1, 2])
    y = np.arange(len(examples))[::-1]
    colors = np.where(examples["dominant_channel"].eq("MAC"), PALETTE["green"], PALETTE["red_light"])
    ax.hlines(y, examples["score_p05"], examples["score_p95"], color=colors, lw=2.4)
    ax.scatter(examples["FCS2"], y, color=PALETTE["ink"], s=14, zorder=3, label="Baseline prior")
    ax.scatter(examples["score_p50"], y, color="white", edgecolor=PALETTE["ink"], s=18, zorder=4, label="Median")
    ax.set_yticks(y, [short_food_name(v, 22) for v in examples["food_name"]])
    ax.set_xlim(0, 101)
    ax.set_xlabel("Score")
    ax.set_title("Real individual score envelopes")
    ax.legend(loc="lower right", fontsize=5)
    panel_label(ax, "d")

    fig.tight_layout()
    save_figure(fig, out_dir, "figure_1_framework")


def figure_2_preservation(source_dir: Path, out_dir: Path) -> None:
    summary = pd.read_csv(source_path(source_dir, "figure2_3_food_summary_v4.csv"))
    group = ordered_groups(pd.read_csv(source_path(source_dir, "figure2_3_food_group_summary_v4.csv")))
    transition = pd.read_csv(source_path(source_dir, "figure2_category_transition_v4.csv"), index_col=0)
    metrics = read_json(source_path(source_dir, "figure2_nps_preservation_metrics.json"))
    boot = pd.read_csv(source_path(source_dir, "figure2_bootstrap_preservation.csv"))

    fig = plt.figure(figsize=(7.4, 5.8))
    gs = fig.add_gridspec(2, 3, height_ratios=[1.35, 1.0], width_ratios=[1.1, 1.0, 1.0])

    ax = fig.add_subplot(gs[0, :2])
    ax.scatter(summary["FCS2"], summary["GMNPS_mean"], s=6, alpha=0.28, color=PALETTE["blue"], linewidths=0)
    ax.plot([1, 100], [1, 100], color=PALETTE["ink"], lw=0.8, ls="--")
    ax.set_xlim(0, 101)
    ax.set_ylim(0, 101)
    ax.set_xlabel("Baseline prior")
    ax.set_ylabel("Population-mean GMNPS")
    ax.set_title("Food-level rank preservation across the scored food universe")
    add_hero_note(
        ax,
        f"n = {int(metrics['n_foods']):,}\nSpearman = {metrics['spearman_fcs2_gmnps_mean']:.6f}\nCategory shifts = {metrics['category_shift_fraction']:.2%}",
    )
    hero_label(ax, "a")

    ax = fig.add_subplot(gs[0, 2])
    matrix = transition.reindex(index=["minimize", "moderate", "encourage"], columns=["minimize", "moderate", "encourage"], fill_value=0)
    row_norm = matrix.div(matrix.sum(axis=1).replace(0, np.nan), axis=0).fillna(0)
    im = ax.imshow(row_norm.to_numpy(), cmap="Blues", vmin=0, vmax=1)
    labels = ["Minimize", "Moderate", "Encourage"]
    ax.set_xticks(range(3), labels, rotation=35, ha="right")
    ax.set_yticks(range(3), labels)
    for row in range(3):
        for col in range(3):
            ax.text(col, row, f"{int(matrix.iloc[row, col]):,}", ha="center", va="center", fontsize=7)
    ax.set_xlabel("GMNPS category")
    ax.set_ylabel("Baseline category")
    ax.set_title("Category transitions")
    fig.colorbar(im, ax=ax, fraction=0.048, pad=0.03)
    panel_label(ax, "b")

    ax = fig.add_subplot(gs[1, :2])
    x = np.arange(len(group))
    ax.plot(x, group["FCS2_mean"], marker="o", ms=3.4, lw=1.2, color=PALETTE["ink"], label="Baseline")
    ax.plot(x, group["GMNPS_mean"], marker="o", ms=3.4, lw=1.2, color=PALETTE["blue"], label="GMNPS mean")
    ax.set_xticks(x, [GROUP_LABELS.get(idx, idx) for idx in group.index], rotation=40, ha="right")
    ax.set_ylabel("Mean score")
    ax.set_title("Food-group ordering")
    ax.legend(loc="upper left")
    panel_label(ax, "c")

    ax = fig.add_subplot(gs[1, 2])
    robustness = pd.DataFrame(
        {
            "label": ["Criterion", "Bootstrap p05", "Observed"],
            "rho": [
                0.90,
                boot["spearman_fcs2_gmnps_mean"].quantile(0.05),
                metrics["spearman_fcs2_gmnps_mean"],
            ],
        }
    )
    y = np.arange(len(robustness))
    ax.hlines(y, 0.90, robustness["rho"], color=[PALETTE["red_light"], PALETTE["blue_light"], PALETTE["blue"]], lw=3)
    ax.scatter(robustness["rho"], y, s=28, color=[PALETTE["red"], PALETTE["blue_light"], PALETTE["blue"]], edgecolor=PALETTE["ink"], linewidth=0.5, zorder=3)
    ax.set_yticks(y, robustness["label"])
    ax.set_xlim(0.885, 1.004)
    ax.set_xlabel("Spearman")
    ax.set_title("Preservation robustness")
    panel_label(ax, "d")

    fig.tight_layout()
    save_figure(fig, out_dir, "figure_2_preservation")


def figure_3_heterogeneity(source_dir: Path, out_dir: Path) -> None:
    summary = pd.read_csv(source_path(source_dir, "figure2_3_food_summary_v4.csv"))
    group = ordered_groups(pd.read_csv(source_path(source_dir, "figure2_3_food_group_summary_v4.csv")))
    heat = pd.read_csv(source_path(source_dir, "figure3_individual_food_delta_heatmap.csv"))

    fig = plt.figure(figsize=(7.4, 5.8))
    gs = fig.add_gridspec(2, 3, height_ratios=[1.36, 1.0], width_ratios=[1.25, 0.9, 0.9])

    ax = fig.add_subplot(gs[0, :2])
    top = summary.sort_values("GMNPS_delta_var", ascending=False).head(14).iloc[::-1]
    y = np.arange(len(top))
    channel_colors = np.where(top["dominant_channel"].eq("MAC"), PALETTE["green"], PALETTE["red"])
    ax.hlines(y, top["GMNPS_p05"], top["GMNPS_p95"], color=PALETTE["blue"], lw=2.1, alpha=0.9)
    ax.scatter(top["FCS2"], y, color=PALETTE["ink"], s=13, label="Baseline")
    ax.scatter(top["GMNPS_mean"], y, color=channel_colors, s=18, label="GMNPS mean")
    ax.set_yticks(y, [short_food_name(v, 35) for v in top["food_name"]])
    ax.set_xlabel("Score")
    ax.set_title("High-heterogeneity foods remain anchored to food-level priors")
    add_hero_note(ax, "Intervals show p05-p95\nacross 15,492 profiles.")
    ax.legend(loc="lower right", fontsize=6)
    hero_label(ax, "a")

    ax = fig.add_subplot(gs[0, 2])
    matrix = heat.pivot(index="individual_order", columns="food_order", values="GMNPS_delta").sort_index()
    im = ax.imshow(matrix.to_numpy(), aspect="auto", cmap="RdBu_r", vmin=-12, vmax=12, interpolation="nearest")
    labels = (
        heat[["food_order", "food_name"]]
        .drop_duplicates()
        .sort_values("food_order")["food_name"]
        .map(lambda value: short_food_name(value, 10))
        .tolist()
    )
    ax.set_xticks(range(len(labels)), labels, rotation=55, ha="right", fontsize=5)
    ax.set_yticks([])
    ax.set_xlabel("Representative foods")
    ax.set_ylabel("Individuals")
    ax.set_title("Individual-food deviation matrix")
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.025, label="Delta")
    panel_label(ax, "b")

    ax = fig.add_subplot(gs[1, 0])
    x = np.arange(len(group))
    ax.bar(x, group["delta_var_mean"], color=PALETTE["blue_light"], edgecolor=PALETTE["ink"], linewidth=0.5)
    ax.set_xticks(x, [GROUP_LABELS.get(idx, idx) for idx in group.index], rotation=40, ha="right")
    ax.set_ylabel("Mean variance")
    ax.set_title("Heterogeneity by food group")
    panel_label(ax, "c")

    ax = fig.add_subplot(gs[1, 1])
    ax.bar(x - 0.18, group["MAC_variance_mean"], width=0.36, color=PALETTE["green"], edgecolor=PALETTE["ink"], linewidth=0.5, label="MAC")
    ax.bar(x + 0.18, group["LIPID_variance_mean"], width=0.36, color=PALETTE["red_light"], edgecolor=PALETTE["ink"], linewidth=0.5, label="LIPID")
    ax.set_xticks([])
    ax.set_ylabel("Mean channel variance")
    ax.set_title("Channel attribution")
    ax.legend(loc="upper left", fontsize=6)
    panel_label(ax, "d")

    ax = fig.add_subplot(gs[1, 2])
    colors = np.where(summary["dominant_channel"].eq("MAC"), PALETTE["green"], PALETTE["red_light"])
    ax.scatter(summary["MAC_variance"], summary["LIPID_variance"], s=6, alpha=0.35, color=colors, linewidths=0)
    lim = float(max(summary["MAC_variance"].quantile(0.995), summary["LIPID_variance"].quantile(0.995)))
    ax.plot([0, lim], [0, lim], color=PALETTE["ink"], lw=0.7, ls=":")
    ax.set_xlim(0, lim)
    ax.set_ylim(0, lim)
    ax.set_xlabel("MAC variance")
    ax.set_ylabel("LIPID variance")
    ax.set_title("Food-level dominance")
    panel_label(ax, "e")

    fig.tight_layout()
    save_figure(fig, out_dir, "figure_3_heterogeneity")


def figure_4_validation(source_dir: Path, out_dir: Path) -> None:
    auroc = pd.read_csv(source_path(source_dir, "figure4_gmrepo_auroc.csv"))
    bench = pd.read_csv(source_path(source_dir, "figure4_synthetic_benchmark.csv"))
    design = pd.read_csv(source_path(source_dir, "figure4_design_ablation.csv"))
    caps = pd.read_csv(source_path(source_dir, "figure4_delta_cap_sensitivity.csv"))
    repeated = pd.read_csv(source_path(source_dir, "figure4_synthetic_repeated_seeds.csv"))

    fig = plt.figure(figsize=(7.4, 5.8))
    gs = fig.add_gridspec(2, 3, height_ratios=[1.28, 1.0], width_ratios=[1.1, 1.0, 1.0])

    ax = fig.add_subplot(gs[0, :2])
    disease_order = ["Healthy_vs_T2D", "Healthy_vs_CAD", "Healthy_vs_CRC", "Healthy_vs_CD", "Healthy_vs_UC", "Healthy_vs_IBD"]
    forest = auroc.set_index("comparison").reindex(disease_order).dropna(subset=["auroc"]).iloc[::-1]
    y = np.arange(len(forest))
    colors = [PALETTE["blue"] if idx in {"Healthy_vs_T2D", "Healthy_vs_CAD"} else PALETTE["gray"] for idx in forest.index]
    ax.hlines(y, forest["auroc_ci_lo"], forest["auroc_ci_hi"], color=colors, lw=2.0)
    ax.scatter(forest["auroc"], y, color=colors, s=28, zorder=3, edgecolor=PALETTE["ink"], linewidth=0.5)
    ax.axvline(0.5, color=PALETTE["ink"], lw=0.8, ls=":")
    ax.set_yticks(y, [idx.replace("Healthy_vs_", "") for idx in forest.index])
    ax.set_xlabel("AUROC versus healthy controls")
    ax.set_title("External microbiome-health plausibility")
    hero_label(ax, "a")

    ax = fig.add_subplot(gs[0, 2])
    order = ["FCS2 only", "unanchored microbiome score", "anchored GMNPS", "random microbiome", "shuffled microbiome"]
    repeated_summary = (
        repeated.loc[repeated["model"].isin(order)]
        .groupby("model", as_index=False)
        .agg(
            individual_response_mean=("individual_response_spearman", "mean"),
            individual_response_sd=("individual_response_spearman", "std"),
        )
        .set_index("model")
        .reindex(order)
        .dropna(how="all")
        .reset_index()
    )
    y = np.arange(len(repeated_summary))
    colors = [PALETTE["gold_light"], PALETTE["red_light"], PALETTE["blue"], PALETTE["gray"], PALETTE["gray"]]
    ax.barh(y, repeated_summary["individual_response_mean"], xerr=repeated_summary["individual_response_sd"], color=colors[: len(repeated_summary)], edgecolor=PALETTE["ink"], linewidth=0.5)
    ax.set_yticks(
        y,
        [
            m.replace("FCS2 only", "baseline\nonly")
            .replace(" microbiome", "\nmicrobiome")
            .replace(" score", "\nscore")
            for m in repeated_summary["model"]
        ],
    )
    ax.set_xlim(0, 1.02)
    ax.set_xlabel("Spearman")
    ax.set_title("Known response across seeds")
    panel_label(ax, "b")

    ax = fig.add_subplot(gs[1, 0])
    ax.scatter(
        bench["nps_preservation_spearman"],
        bench["personalized_residual_spearman"],
        s=28,
        color=PALETTE["gray"],
        edgecolor=PALETTE["ink"],
        linewidth=0.5,
    )
    for model, color in [("anchored GMNPS", PALETTE["blue"]), ("unanchored microbiome score", PALETTE["red"])]:
        row = bench.loc[bench["model"].eq(model)].iloc[0]
        ax.scatter(row["nps_preservation_spearman"], row["personalized_residual_spearman"], s=54, color=color, edgecolor=PALETTE["ink"], linewidth=0.6, label=model)
    ax.set_xlim(0.925, 1.004)
    ax.set_ylim(0, 0.43)
    ax.set_xlabel("Prior preservation")
    ax.set_ylabel("Residual recovery")
    ax.set_title("Trade-off")
    ax.legend(loc="upper left", fontsize=6)
    panel_label(ax, "c")

    ax = fig.add_subplot(gs[1, 1])
    d_order = ["FCS2 only", "anchored GMNPS", "no centering", "unanchored microbiome score", "random microbiome", "shuffled microbiome"]
    d = design.set_index("model").reindex(d_order).dropna(how="all").reset_index()
    x = np.arange(len(d))
    residual = d["personalized_residual_spearman"].fillna(0)
    preservation = d["nps_preservation_spearman"]
    ax.bar(x - 0.17, residual, width=0.34, color=PALETTE["blue"], edgecolor=PALETTE["ink"], linewidth=0.5, label="Residual")
    ax.bar(x + 0.17, preservation, width=0.34, color=PALETTE["green_light"], edgecolor=PALETTE["ink"], linewidth=0.5, label="Preservation")
    ax.text(-0.17, 0.04, "NA", ha="center", va="bottom", rotation=90, fontsize=6)
    ax.set_ylim(0, 1.05)
    ax.set_xticks(
        x,
        [
            str(v)
            .replace("FCS2 only", "baseline only")
            .replace(" microbiome", "\nmicrobiome")
            .replace(" score", "\nscore")
            for v in d["model"]
        ],
        rotation=35,
        ha="right",
    )
    ax.set_ylabel("Spearman")
    ax.set_title("Ablation")
    ax.legend(loc="upper left", fontsize=6)
    panel_label(ax, "d")

    ax = fig.add_subplot(gs[1, 2])
    ax.plot(caps["delta_cap"], caps["personalized_residual_spearman"], marker="o", ms=4, color=PALETTE["blue"], lw=1.2, label="Residual")
    ax.plot(caps["delta_cap"], caps["nps_preservation_spearman"], marker="o", ms=4, color=PALETTE["green"], lw=1.2, label="Preservation")
    ax.set_xlabel("Deviation cap")
    ax.set_ylabel("Spearman")
    ax.set_ylim(0.35, 1.02)
    ax.set_title("Cap sensitivity")
    ax.legend(loc="center right", fontsize=6)
    panel_label(ax, "e")

    fig.tight_layout()
    save_figure(fig, out_dir, "figure_4_validation")


def export_source_manifest(source_dir: Path, out_dir: Path) -> None:
    copied_dir = out_dir / "source_data"
    copied_dir.mkdir(parents=True, exist_ok=True)
    for path in sorted(source_dir.iterdir()):
        if path.is_file() and path.suffix.lower() in {".csv", ".json", ".md"}:
            shutil.copy2(path, copied_dir / path.name)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create draft Nature-style GMNPS main figures from source data")
    parser.add_argument("--source-dir", default="outputs/nature_source_data_v2")
    parser.add_argument("--output-dir", default="outputs/nature_figures_v2")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    source_dir = Path(args.source_dir)
    out_dir = Path(args.output_dir)
    set_style()
    figure_1_framework(source_dir, out_dir)
    figure_2_preservation(source_dir, out_dir)
    figure_3_heterogeneity(source_dir, out_dir)
    figure_4_validation(source_dir, out_dir)
    export_source_manifest(source_dir, out_dir)


if __name__ == "__main__":
    main()
